/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_TUTORIAL_TYPE_DEFINITIONS_H__
#define __RS_TUTORIAL_TYPE_DEFINITIONS_H__

#define RS_TUTORIAL_TEST_CENTROID "rs_tutorial.test.Centroid"
#define RS_TUTORIAL_TEST_MYFIRSTANNOTATION "rs_tutorial.test.MyFirstAnnotation"

#endif /* __RS_TUTORIAL_TYPE_DEFINITIONS_H__ */
